import angular from 'angular';

// Import our app config files
import constants from './config/app.constants';
import appConfig from './config/app.config';
import appRun from './config/app.run';

import 'angular-ui-router';
import 'angular-utf8-base64';
import 'angular-animate';

// Import our templates file (generated by Gulp)
import './config/app.templates';

// Behavior of the site
import './components'; // load ./components/index.js to get all components
import './errors/403';
import './errors/404';
import './errors/500';

// Utilities
import './services';
import './directives';

import './pages/home';

// Create and bootstrap application
const requires = [
    'ui.router',
    'utf8-base64',
    'ngAnimate',
    'templates',
    'app.components',
    'app.home',
    'app.services',
    'app.directives',
    'app.errors.403',
    'app.errors.404',
    'app.errors.500'
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
    strictDi: true
});
